modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT License"

[[mods]]
modId = "cobblemontrainerscaling"
version = "${version}"
displayName = "Cobblemon Exp All"
authors = "damnnnnsam"
description = '''
A cobblemon sidemod for implementing the exp all mechanic from the main games
'''

[[dependencies.cobblemontrainerscaling]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemontrainerscaling]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemontrainerscaling]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.1,)"
ordering = "AFTER"
side = "BOTH"